# Generated by Django 6.0.2 on 2026-03-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='moneda',
            field=models.CharField(default='COP', max_length=10),
        ),
    ]
